### ISSUE TITLE
Twitter Kapak

### ISSUE THREAD

**Issue by productdevbook** [afetcan/design#1]
depremde ihtiyac duyulan ana temelleri yan ana iconlar konularak kisa ve oz anlatan bir calisma olabilir
gida, enkaz altinda yardim, barinma ...

**Comment by kivilcimcagatay** [comment]
https://www.figma.com/file/nsffCyQJY5rSJpjEIMiSij/acildeprem?node-id=9%3A3&t=XqD0eEG7X4vzs8GN-1 paylaştığın figmaya ekledim

**Comment by productdevbook** [comment]
Eyvallah

![image](https://user-images.githubusercontent.com/38668796/217354880-db0a2f4c-5b5b-428a-9eba-fd8310ea1c27.png)

Bu sekilde duzeldim twitterda ekliyorum hemen. Ellerinize saglik. Harika
