### ISSUE TITLE
Site ile İlgili Bulgular/Öneriler

### ISSUE THREAD

**Issue by bceyhan3** [afetcan/design#5]
1.  Bu ekranda yardım edin butonuna basıldıktan sonra chatbot gelmesi, yardımı yapacak kişi için yol gösterici değil. Burada kategorilere ayırmak daha verimli olacaktır. 
![image](https://user-images.githubusercontent.com/52166558/218324295-df16de44-296c-49e2-b0d6-8387d6a5e170.png)

2. Bu bilgiye ihtiyaç olduğunu düşünmüyorum. İlla verilmek isteniyorsa da son cümle en önemlisi olduğu için bu cümle ön plana çıkarılmalı.
![image](https://user-images.githubusercontent.com/52166558/218324453-46b2cedf-f39b-4f42-8735-51dd2e8cd575.png)
Hayır Kurumları butonuna basıldığında doğrudan bu bilgiler gelirse daha iyi olur.
![image](https://user-images.githubusercontent.com/52166558/218324887-02150c65-30cc-48b7-892c-de209623658e.png)

3.Bu şekilde tooltipler kullanılırsa kullanıcı için yol gösterici olabilir
![Group 2 (1)](https://user-images.githubusercontent.com/52166558/218325295-004d9d1c-43e8-457b-a3b0-b2ac977749c5.png)

4. İngiltere bayrağı ile değiştirilmeli
![image](https://user-images.githubusercontent.com/52166558/218325361-783c73a2-b319-41e6-8058-ec8b4872bf6e.png)

5. Yardım kuruluşları denilirse daha anlaşılır olacaktır
![image](https://user-images.githubusercontent.com/52166558/218325430-fe461d48-b236-4359-8866-312a1a6ea11a.png)
![image](https://user-images.githubusercontent.com/52166558/218325457-ce0a4309-faf8-4cf5-8922-66202437c299.png)

6.İlk maddede yazdığıma ek olarak, genel olarak chatbox yerine form doldurup gönderme temelli yapılırsa kullanıcı açısından daha kolay ve takip edilebilir olacaktır.

**Comment by productdevbook** [comment]
Web tarafina ilettim bunu orada issua acildi. Zamani gelince duzeltmeleri yapacagiz. 

Yureginize saglik

**Comment by productdevbook** [comment]
Bitirdik tekrardan goz atip gerekli degisiklikleri bize yeni issuada bildirebilirsiniz.

Ellerinize saglik
